# Tutorial 2: Pandas
-----------------------------------------------
## Overview
NumPy is very fast at handling data. However, it is limited by allowing only ONE data type. Pandas adds the familiar data structure like a spreadsheet, with data organized in rows and columns with names. Why not just use Excel or Sheets, then? Because bioinformatics data sets, such as RNAseq results, are so large and you may need to do complex calculations on the data. Python tools are much faster, more powerful and more flexible than pre-packaged spreadsheet tools. 
### Learning Objectives

After this tutorial, you will be able to:
- Define "dataframe"
- Create a Pandas dataframe from scratch or from imported data
- Work with column and rows
- Sort, organize, query, and manipulate the Pandas dataframe
    
### Prerequisites

- Introductory Python
- NumPy (tutorial 2)

### Getting Started
* One way to get introduced to Pandas is provided by pydata: [10 minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html) or their [getting started tutorials](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html)
* Watch the brief Lecture
* As with NumPy, the custom is to import pandas with the alias of pd to save your typing time.

In [329]:
#Run this code box to install required packages
%pip install jupyterquiz
import seaborn as sns
import pandas as pd
from jupyterquiz import display_quiz
import os
print("All needed tools imported")

Requirement already satisfied: jupyterquiz in c:\users\jrcha\anaconda3\lib\site-packages (2.6.3)Note: you may need to restart the kernel to use updated packages.
All needed tools imported

## Why Pandas?​

The scripting in Python is good till now, but what about data organization or handling columns of tabular data with different types? ​

Pandas focuses on **data management** which can be combined with **analytics tools**​

The core data type is a DataFrame. A DataFrame organizes data into rows and columns, making it easy to access, filter, and process.
![Structure of a Dataframe](pandasDF.png)

You can think of it like an Excel spreadsheet or (more appropriately) like a database table​
  - Tabular​
  - Same data type within Column, but the data type can vary by column​

## Why use DataFrames in Bioinformatics?

In bioinformatics, data often comes in tabular formats, such as gene expression matrices, genomic variant tables, or protein interaction datasets. A Pandas DataFrame provides:

1. Ease of Handling Tabular Data:
    - Rows can represent biological samples, sequences, or variants.
    - Columns can represent genes, features, or metadata.
    - Unlike Excel, Pandas does not attempt to display all the values all the time, so it is less demanding on computer memory-- especially for the large datasets common to bioinformatics

2. Data Analysis: Perform operations like filtering, grouping, and summarizing efficiently.
    - Example: Find the top 10 most expressed genes in RNA-Seq data.

3. Integration: Read/write to biological data formats like CSV, Excel, or SQL.
    - Example: Import genomic data from a CSV file and perform preprocessing.

4. Visualization: Easily integrate with visualization libraries like Matplotlib
    - Example: Plot expression levels of genes across conditions.
    - Since Matplotlib can produce HIGH resolution images, this is a helpful tool for producing publication-ready figures

### Creating Data Frames

A Pandas dataframe can be constructed in many ways. (see [pandas documentation](https://pandas.pydata.org/docs/user_guide/dsintro.html#dataframe) for more ways). Each column is called a **Series** and has it's own functions in Pandas [see more]
We can create a dataframe by passing in a dictionary of equal length lists​

  * The dictionary keys will be column names​

We can also create dataframes from file loads and queries

Here, you see how it is made with a dictionary as the data that you might assemble yourself.

In [333]:
# Make Dataframe
import pandas as pd 
import numpy as np
np.random.seed(123)
data = {'id': list(range(1,11)),
'yr': list(range(2015,2020))*2,
'count': np.random.randint(10,40,10)}
frame = pd.DataFrame(data)
frame

   id    yr  count
0   1  2015     23
1   2  2016     12
2   3  2017     38
3   4  2018     12
4   5  2019     16
5   6  2015     27
6   7  2016     29
7   8  2017     20
8   9  2018     37
9  10  2019     35

### Importing structured data sets (e.g. CSV)

Probably the most common way to create a Pandas dataframe is to **import a CSV** for further analysis. ​

You can also import excel, JSON, and the clipboard. [All the data types and import methods](http://pandas.pydata.org/pandas-docs/stable/io.html)

Try the next box to import a portion of a large cancer dataset.

In [335]:
exercise = sns.load_dataset("exercise")

### A sample dataset: states
Before we tackle bioinformatics datasets, it is customary to work with a toy dataset for which we have some intuition. A dataframe of information about the US states will allow you to learn and practice some Pandas skills.

In [337]:
# Import a csv file as a Pandas Dataframe
states = pd.read_csv(".\Datasets\states.csv")

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\jrcha\AppData\Local\Temp\ipykernel_23164\2296371485.py:2: SyntaxWarning: invalid escape sequence '\D'
  states = pd.read_csv(".\Datasets\states.csv")

As soon as we import data, step one should be to check the data import​. Look at the first rows (5 is default, or you can specify with df.head(n=)

In [339]:
# View
states.head(n=3)
#states.tail(n=5)

,State,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
0,Alabama,3615,3624,2.1,69.05,15.1,41.3,20,50708
1,Alaska,365,6315,1.5,69.31,11.3,66.7,152,566432
2,Arizona,2212,4530,1.8,70.55,7.8,58.1,15,113417

## Pandas tools

### Summary Statistics
Are the number of rows as expected? What about the column names? General range of continuous variables? It's easy to asses​s

A Pandas dataframe  has a method (df.describe()) that can easily summarize each column. *The summary information is itself a dataframe*

In [342]:
states.describe()

,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
count,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,4246.420000,4435.800000,1.170000,70.878600,7.37800,53.108000,104.460000,70735.880000
std,4464.491433,614.469939,0.609533,1.342394,3.69154,8.076998,51.980848,85327.299622
min,365.000000,3098.000000,0.500000,67.960000,1.40000,37.800000,0.000000,1049.000000
25%,1079.500000,3992.750000,0.625000,70.117500,4.35000,48.050000,66.250000,36985.250000
50%,2838.500000,4519.000000,0.950000,70.675000,6.85000,53.250000,114.500000,54277.000000
75%,4968.500000,4813.500000,1.575000,71.892500,10.67500,59.150000,139.750000,81162.500000
max,21198.000000,6315.000000,2.800000,73.600000,15.10000,67.300000,188.000000,566432.000000

### Rows and Columns 

We also may want to look at just the list of row identifiers (names), or column names. These are stored as attributes of the Pandas dataframe, so we can access the array

These “index” objects have a .values attribute if we want just a list, instead of an “index” object. 

As with np arrays, you can reference different dimensions.  **df.loc** attribute accesses a group of rows and columns by label(s) or a boolean array in the given DataFrame:
df.loc [:, range] selects a set of columns
df.loc[range,:] selects a set of rows​

**df
.iloc**() index by integer location, similar to numpywhile ​**df

.l**oc() index by label location (end inclusive)​

In [344]:
# List Columns
states.columns

#Take a slice of columns

#states.loc[0:8,'Population':'Illiteracy']
#states.loc['Population':'Illiteracy']
#states.loc[3:7,:]
#states[3:7]

# List row IDs
#states.index   # shows as a formula

Index(['State', 'Population', 'Income', 'Illiteracy', 'Life Exp', 'Murder',
       'HS Grad', 'Frost', 'Area'],
      dtype='object')

### Test your knowledge
*run the next box for a quiz*

In [389]:
import os
from jupyterquiz import display_quiz
indqz = "." + os.sep + "PythonQuizQuestions" + os.sep + "pandas_index.json"
display_quiz(indqz)

### Indexes

We can select portions of the data fram by indexes (rows and columns) in a variety of ways (some of which may seem inconsistent.) ​

In [346]:
# Indexing
# Select Column
states['State']
# Or select more than one column
#states[['Area', 'State']]
 
# By column name attribute
states.State[0:6]

0       Alabama
1        Alaska
2       Arizona
3      Arkansas
4    California
5      Colorado
Name: State, dtype: object

In [347]:
# Indexing
# Or select more than one column
states[['Area', 'State']]
 
# By column name attribute
states.State[0:6]

0       Alabama
1        Alaska
2       Arizona
3      Arkansas
4    California
5      Colorado
Name: State, dtype: object

In [348]:
# Indexing
# Or by row, which is technically an attribute of the column data
states.State[0:6]

0       Alabama
1        Alaska
2       Arizona
3      Arkansas
4    California
5      Colorado
Name: State, dtype: object

In [349]:
# Select Row (labels, index)
states[0:2]

,State,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
0,Alabama,3615,3624,2.1,69.05,15.1,41.3,20,50708
1,Alaska,365,6315,1.5,69.31,11.3,66.7,152,566432

We can also index with **boolean​s**

In [351]:
# select by boolean characteristics
states[states.Murder <= 2.7]

,State,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
14,Iowa,2861,4628,0.5,72.56,2.3,59.0,140,55941
18,Maine,1058,3694,0.7,70.39,2.7,54.7,161,30920
22,Minnesota,3921,4675,0.6,72.96,2.3,57.6,160,79289
33,North Dakota,637,5087,0.8,72.78,1.4,50.3,186,69273
38,Rhode Island,931,4558,1.3,71.90,2.4,46.4,127,1049
40,South Dakota,681,4167,0.5,72.08,1.7,53.3,172,75955

## Test your Knowledge
> 1. Efficiently determine how many states have a life expectancy between 70 and 71
> 2. What is the average HS Graduate percentage for these states?

In [353]:
#Run this code box for a quiz
from jupyterquiz import display_quiz
import os
lenqz= "." + os.sep + "PythonQuizQuestions" + os.sep + "pd_boolean_lengthQz.json"

display_quiz(lenqz)

In [354]:
#Answers
x=states.loc[(states['Life Exp']>71) & (states['Life Exp']>70)]
len(x)
#x['HS Grad'].mean()

20

In [355]:
# select by integer location
states.iloc[0:3,0:4] #not end inclusive
 
# select by label only
states.loc[0:15,"Population":"Life Exp"]
# end inclusive

    Population  Income  Illiteracy  Life Exp
0         3615    3624         2.1     69.05
1          365    6315         1.5     69.31
2         2212    4530         1.8     70.55
3         2110    3378         1.9     70.66
4        21198    5114         1.1     71.71
5         2541    4884         0.7     72.06
6         3100    5348         1.1     72.48
7          579    4809         0.9     70.06
8         8277    4815         1.3     70.66
9         4931    4091         2.0     68.54
10         868    4963         1.9     73.60
11         813    4119         0.6     71.87
12       11197    5107         0.9     70.14
13        5313    4458         0.7     70.88
14        2861    4628         0.5     72.56
15        2280    4669         0.6     72.58

### Adding/Deleting

We can add columns by selecting a new column, then assigning a value​

Note we cannot use the column attribute to create a new column​

Use the **del** keyword to delete a column​

In [357]:
# Add Column
states["NewCol"] = 4
states.head()
 
# Delete Column
del states["NewCol"]
states.head()

,State,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
0,Alabama,3615,3624,2.1,69.05,15.1,41.3,20,50708
1,Alaska,365,6315,1.5,69.31,11.3,66.7,152,566432
2,Arizona,2212,4530,1.8,70.55,7.8,58.1,15,113417
3,Arkansas,2110,3378,1.9,70.66,10.1,39.9,65,51945
4,California,21198,5114,1.1,71.71,10.3,62.6,20,156361

We can delete rows or columns with **.drop**​

We can add rows or columns with **.append** ​

Columns as well.​

In [359]:
# Delete Row/Add Row
states.drop(states.index[0])
states.drop(states.index[-1])
states1 = states[0:10]
states2 = states[10:25]
states3 = states[25:]
states1.append([states2,states3])

AttributeError: 'DataFrame' object has no attribute 'append'

### Reindexing After Subsetting

We often take a subset of a dataframe, and we may need to **reindex** the rows afterwards. ​

This is not done automatically post subset.​

In [ ]:
# Reindex
states.sub = states[states.Population < 1000]
states.sub = states.sub.reset_index()
del states.sub["index"]
states.sub 

# Alternatively
states.sub = states.sub.reset_index(drop=True)

## Dealing with Missing Values 

Pandas uses NaN to cover missing values​

You can drop missing data axis (rows or cols) with **.dropna()**

You can fill missing values in with **fill.na()**

There is a built in method for forward fill or back fill​

In [ ]:
# Missing Data
states_miss  = states.copy()
# Set all Population values below 1000 to missing
states_miss["Population"][states["Population"] < 1000] = np.NaN
states_miss.Population[states.Population < 1000] = np.NaN
# drop missing data
states_miss.dropna()
states_miss.fillna(0)
states_miss.fillna(method="ffill")

We use **.isnull()** and **.notnull()** to check for missing values (boolean result)​

In [ ]:
# isnull
states_miss.isnull()
states_miss.notnull()

# How would we check which rows are null?

## Running unctions on DF

Lets think of functions in terms of number of inputs relative to number of outputs​

- Functions which return one output for each input operate elementwise​
- Functions which reduce a list of inputs to 1 output operate column-wise (by defult)​

In [ ]:
# Functions on DataFrames
states.mean()

In [ ]:
# Functions on DataFrames
states.mean()
#Whats the Difference between these two?
states.mean()["Population"]
states["Population"].mean()
 
# Returning More than One Value
states_cop = states.copy()
res = states_cop.ix[:,"Population" : "Illiteracy"].diff()
pd.concat([states_cop.ix[:,"State"],res],axis=1)

Vectorization in Pandas can handle a wide variety of situations​

You can apply functions to Pandas objects in three ways:​

  - Table-wise using **pipe()**

  - Row or column-wise using **apply()**

  - Element-wise using **applymap()**
  
Use table-wise functions to operate on an entire dataframe​

In the sample below, we add a number to each element in the table (in this case, 2)

In [ ]:
import pandas as pd
import numpy as np

def adder(ele1,ele2):
    return ele1+ele2

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.pipe(adder,2)
print(df.apply(np.mean))

By row-wise or column-wise, what we mean is applying a function along a particular axis​

Which means we can use this in higher-order matrices too​

Each axis has an index. List the index to set the application​

Columns is index 0 and default​

Rows is index 1​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.apply(np.mean)
print(df.apply(np.mean))

Doing an element-wise operation is the same as our original notion of vectorization​

Note in the sample here we are combining a table-wise and element-wise operation as a comparison​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
print(df.apply(np.mean))    # old mean
print(df.applymap(lambda x:x*100)) # modify elements
print(df.applymap(lambda x:x*100).apply(np.mean)) # new mean

## Sorting a DF 

We use **.sort_values()** to sort a data frame​

We can sort by either the index or a column(s)​

In [ ]:
# Sorting
states.sort_values("Population")
states.sort_values("Population“, ascending=True)

# Multiple sorts
states.sort_values(by=["Illiteracy","Population"]) states.sort_values(by=["Illiteracy","Population"],
ascending=[True,False])

Iterating over a series (1d) object is similar to an array or tuple​

Iterating over a dataframe or panel is a little trickier​

The iteration for them provides a dictionary object which has the columns/values of rows/values​

  - Use iteritems() for column-wise​

  - Use iterrows() for row-wise​

  - User itertuples() to convert rows to tuples​
  
The **iteritems()** method produces key, value pairs with the column name and the column values as a series​

In [ ]:
import pandas as pd
import numpy as np
 
df = pd.DataFrame(np.random.randn(4,3),columns=['col1','col2','col3'])
for key,value in df.iteritems():
    print(key,value)

The **iterrows()** method returns a dictionary with each key, value pair as a row index and a series of row values​

Each value is associated with its specific column label​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(4,3),columns = ['col1','col2','col3'])
for row_index,row in df.iterrows():
    print(row_index, row)

## Unique Values

We can use the .unique() function of Series to Get unique values from a column​

Use the sorted function to sort the output from unique

In [ ]:
# Unique Values
states["Illiteracy"].unique()

# Unique Values from data set
states.drop_duplicates()

## Merge

It might be useful to merge two dataframes together.  You need to picture them & ask yourself how they should be arranged- which of the 2 on the left & which on the right. 

To merge them together, we can use the **pd.merge()** function & specify "where" each one goes. See the syntax below.

In [ ]:
# Import Dataframe
states = pd.read_csv(r"C:\data\states.csv")
states2 = pd.read_csv(r"C:\data\states_extra.csv")

# Merge these together
pd.merge(states,states2,how="left", left_on="State",right_on=“ST")

### Reshaping 

We often want to “reshape” a matrix​

A specific example would be “pivoting” (pivot tables anyone?)​

Another often used reshape is going from “long” to “wide”, and vice versa. ​

Finally, we may wish to transpose a dataframe or matrix​

There are other more complex reshaping use cases, but we will only briefly cover them​

We can “Stack” and “unstack” data frames​

In [ ]:
# reshaping a dataframe
state_sub = states.ix[0:3,1:3].copy()
state_sub.index = states.State[0:4]
state_sub.stack()
state_sub.stack().unstack()

# Can specify which dimension to unstack
state_sub.stack().unstack(0)
state_sub.stack().unstack(1)

#### Reshaping from Long to Wide 

We have data indexed by a repeated variable (id) and another variable (time), with other values

In [ ]:
# Long to Wide
df = pd.DataFrame({"id": 	("a","a","b","b","c","c"),                   	"time": (1,2,1,2,1,2),
	"meas":range(6)})
wide = df.pivot("id","time","meas")

#### Reshaping from Wide to Long</div> 

We may wish to go back from Wide to Long

In [ ]:
# Wide to Long
wide["id"] = wide.index


pd.melt(wide,id_vars=["id"],
        value_vars=[1,2],var_name="Time",value_name="meas")

## Data wrangling
### Removing Duplicates</div> 

Duplicates in a Pandas DataFrame can be problematic for several reasons, depending on the context of your analysis or data manipulation.

It might mean
1. Data Integrity Issues
2. Increased Storage and Processing
3. Impact on Data Validation
4. Issues with Data Joins or Merges
5. Reduced Data Quality
6. Challenges in Machine Learning

Fortunately, Pandas has a simple way to manage these: 

- df.duplicated(): Identifies duplicate rows.
- df.drop_duplicates(): Removes duplicate rows.
- df.duplicated(subset=[...]): Checks for duplicates in specific columns only.

In [ ]:
# Duplicates
df_dup  = df.append(df.iloc[1]) # this adds the 

df_dup.duplicated()

df_dup.drop_duplicates()

<div style="font-size:18px">Making categories</div> 

It might be that you need to divide your data into groups. For example, if you have a patient data set with the exact values of their temperatures, but you really just need to know "normal, fever, severe fever" as categories. Here we can show it this, too, with our states data. ​

We can use **dataframe.cut()**

You describe the bins (this process can be called "binning") and assign names to the categories.

In [ ]:
# binning with cut
states.Population.describe()
bins = [0,1000,3000,5000,25000]
pd.cut(states.Population, bins)

# With Labels
states['Population_cat']= pd.cut(states.Population, bins, 
                                 labels=["small","med","large","huge"])

<div style="font-size:18px">Working with Text</div> 

Strings in Pandas are roughly the same as strings in Python​

We simply operate on series rather than a single object​

Pandas provides many of the same methods, such as **len()**, **lower()**, **upper()**, **split()** and others you have seen before​

Pandas methods also usually ignore missing NaN values​

In [ ]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t'
               , np.nan, '1234','SteveSmith'])

print(s)
print(s.str.lower())
print(s.str.upper())
print(s.str.len())

We often want to apply functions to groups within our dataset. ​

  - What is the mean value within group?​

  - What is the variance within group?​

  - Perform a linear regression within group, then get the slope estimates out.​

This has been conceptualized as:​

  - Split​

  - Apply​

  - Combine​
  
<div style="font-size:18px">Group-wise Operation</div>

The first step is to establish the groups (SPLIT)​

In Pandas, we can use the **.groupby()** method for this​

Use states, and group on the variable we just created ​

In [ ]:
# Group By
grp = states.groupby("Population_cat")
grp.mean()
grp.var()
 
# Only One variable
states.Income.groupby(states.Population_cat).mean()

We can index the group-by with a dynamically created value

In [ ]:
# Group By Dynamic Variables
states.Illiteracy.groupby(states.Income < 4100).mean()

We can iterate through the groups, allowing more flexibility to do things

In [ ]:
# Group By Iteration
# we need to convert the series 
# to a bunch of # strings so we can grab the first letter
states['firstlet']= states.State.astype(str).str[0]
grp = states.groupby("firstlet")
for (name,data) in grp:
    print(name)
    print(data)

<div style="font-size:18px">Aggregation</div> 

Use **grp.agg()** to pass in user written function​

**groupedobj.agg(function)**​

You can also pass in a list of length two tuples with names and functions to name the columns. ​

In [ ]:
# Aggregation
# Write your own function
def sterr(x):
    try:
        return np.std(x) / np.sqrt(len(x))
    except:
        return np.nan
sterr(states.Income)
grp = states.groupby(states.Income < 4100)["Illiteracy"]
grp.agg(sterr)
grp.agg([(“spread",sterr),
	   (“center",np.mean)])

<div style="font-size:18px">Use Vars instead of Index</div>

We can request the group by object returns variables (columns) instead of index or hierarchical indexes

In [ ]:
# Eliminate the index
grp = states.groupby(states.Income < 4100,as_index=False)
grp.mean()

<div style="font-size:18px">Joining Groupwise Aggregations</div> 

After calculating groups means, we may wish to rejoin them to the group. ​

Pandas calls this “transform”, where the transformed data is placed back in the context of the original data. ​

The result must be a scalar, or the appropriate sized array.

In [ ]:
# Transform 
grp = states.groupby(states.Income < 4100,as_index=False)["Illiteracy"]

grp.transform(np.mean)

<div style="font-size:18px">Cross Tabs</div>

Frequency Table

Classic statistical aggregation. How many observations occupy each group?

In [ ]:
# Cross Tabs 
pd.crosstab(states.Income < 4100,states. Population_cat) 
pd.crosstab(states.Income < 4100,states. Population_cat,margins=True)

<div style="font-size:18px">Applying Functions</div> 

How could we get the percentages rather than the frequencies?​

We can apply a function across rows or columns using **pd.apply()**

In [ ]:
# Create the table
tbl1 = pd.crosstab(states.Income < 4100,states.Population_cat)

# Applying Functions
tbl1.apply(lambda x: x/x.sum(),axis=0)
tbl1.apply(lambda x: x/x.sum(),axis=1)

Because we do a lot of data analytics with Pandas, it’s good to know some statistics​

  - Pandas supports all the basics​

  - Mean, median, mode, min, max​

  - Covariance, Correlation, Ranking

In [ ]:
s = pd.Series([1,2,3,4,5,4])
print(s.pct_change())
print(s.cov(s2))

df = pd.DataFrame(np.random.randn(5, 2))
print(df.pct_change())
print(df.mean())
print(df.median(axis=1))
print(df.mode(axis=1))

<div style="font-size:18px">Correlation</div> 

A quick note on correlation. Correlation shows the linear relationship between two series​

There are multiple ways to compute the correlation like pearson, spearman and kendall​

  * Pearson is the default​

Correlate a pair of rows or the entire dataframe​

In [ ]:
frame = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 
                                                      'd', 'e'])

print(frame['a'].corr(frame['b']))
print(frame.corr())

### Data Ranking 

Sometimes we want to “rank” our rows in order to see how they compare with the rest of the data​

  - Best sales overall or by month or year​

  - Fastest completion times, best gas mileage, etc.​

Ties are handled according to a method parameter (average, min, max, first)​

  - The default is to average ties​

In [ ]:
s = pd.Series(np.random.np.random.randn(5), index=list('abcde'))
s['d'] = s['b'] # so there's a tie
print(s.rank())

## Pandas Visuals 

We have a whole section on visuals, but because it is so important to data analytics, pandas provides visuals too​

Pandas supports many types of plots​

  - Line, bar, area, box, histogram and scatter plots among others

In [ ]:
df = pd.DataFrame(np.random.randn(10,4),
        index=pd.date_range('1/1/2000',
        periods=10), columns=list('ABCD'))

df.plot()

In [ ]:
df = pd.DataFrame(np.random.rand(10,4),
        columns=['a','b','c','d'])
df.plot.bar()

In [ ]:
# stacked bar
df.plot.bar(stacked=True)

In [ ]:
# horizontal stacked bar
df.plot.barh(stacked=True)

In [ ]:
df = pd.DataFrame({'a':np.random.randn(1000)+1
                   ,'b':np.random.randn(1000),'c':
np.random.randn(1000) - 1}, columns=['a', 'b', 'c'])
# histogram
df.plot.hist(bins=20)

In [ ]:
df = pd.DataFrame(np.random.rand(50, 4)
    , columns=['a', 'b', 'c', 'd'])
df.plot.scatter(x='c', y='b')
df.plot.box()

In [ ]:
df = pd.DataFrame(3 * np.random.rand(4)
    , index=['a', 'b', 'c', 'd'], columns=['x'])
df.plot.pie(subplots=True)

Time for some bioinformatics exercises!

# Test Your Knowledge

Create a function to:

> 1. Take an array as input (from a data frame)
> 2. Output the mean, median, and a sorted list of unique values

# Conclusion
You now have tools to do a LOT of manipulations of data frames with Pandas in Python. You are ready for a bioinformatics exercise. 

If you do not want to practice at this point, the next tutorial picks up with how to [visualize your data](./Submodule_2_Tutorial3_VisualizingData.ipynb) with graphs in matplotlib

## Clean up
Remember to stop your Jupyter Notebook compute instance to avoid unnecessary charges..